services:
  - type: web
    name: kalki-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn app:app -b 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OAUTHLIB_INSECURE_TRANSPORT
        value: 1
